# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6adb0d97dd29adab8e5048d27aed33113600af0422aec6abe224aa4a93e8a11b460d9eaa09f5cc8aabe2a3bcff1a955189e4d0b901a2b48d61ac107e35cc0c12

test:
  secret_key_base: e9ca9326935c8e837a8e37ce5cf0c839265cd41b1aea9badc16373d8bf1eff50af79643e7f045317280758bbdad41bd9ab94e439e1141bad07872d763f24c483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
